### ISSUE TITLE
Validate protocol version in decoder 

### ISSUE THREAD

**Issue by gazwald** [quakeservices/master#107]
How much value does this have given we only know the protocol on `heartbeat` requests?

**Comment by darkshade9** [comment]
Is the `protocol` value in heartbeat requests not the same as the actual server `protocol`?  I notice our latest protocol 38 servers return as `34`, but that could be something we missed on our end?

**Comment by gazwald** [comment]
The protocol in the `heartbeat` is `34`. I figure this is mostly to maintain compatibility with other Quake 2 clients/servers/etc.

As far as I can tell there aren't any tangible differences between the vanilla, Q2Pro, or r1ch (need to confirm) protocols as far as the master server is concerned.

It's been a _very_ long time since a looked at the code that was available for the other master servers but I don't recall them differentiating either.
